### ISSUE TITLE
BUG: Some Vignettes don't run

### ISSUE THREAD

**Issue by rhine3** [vocalpy/crowsetta#220]
**Describe the bug**
While testing the package for PyOpenSci I had some trouble getting the following vignettes to run. To keep this organized in one compact issue, I'll use the "To Reproduce" section to describe the issues.

**To Reproduce**
* Create `conda` environment: `conda create -n crowsetta_review`
* Activate environment: `conda activate crowsetta_review`
* Use `conda` to install Crowsetta from `conda-forge`: `conda install crowsetta -c conda-forge`
* Open Python interpreter in terminal: `python`
* Copy/paste the vignette text into the Python interpreter

What happened for each vignette:
- Vignette “How to convert sequence-like annotations to the 'simple-seq' format” runs successfully locally.
- Vignette “How to use crowsetta with your own annotation format” didn’t run successfully locally because the example file `bat1_annotation.mat` was not included in the tutorial
- Vignette “How to convert any sequence-like format to 'generic-seq'” can’t be run entirely locally. I get an error when running the following line in two places in the vignette:
```
df = generic.to_df()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GenericSeq' object has no attribute 'to_df'
```
- Vignette “How to use crowsetta to remove unlabeled intervals from TextGrid annotations” can’t be run exactly as written locally because the standard conda install of crowsetta didn't include one of the required packages for installing the data, `osfclient`. Perhaps just add an “install osfclient” suggestion to the vignette and that would be good to go. Also, I found that the large code block containing functions wouldn't correctly copy/paste into the interpreter; not sure why.
```
>>>     # set of (unique) states
>>>     states = sorted(
  File "<stdin>", line 1
    states = sorted(
IndentationError: unexpected indent
```

**Expected behavior**
See above.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Operating System: Mac
 - Version: `4.0.0.post2`

**Additional context**
I created this issue while performing the [PyOpenSci review of this package](https://github.com/pyOpenSci/software-submission/issues/68).

**Comment by NickleDave** [comment]
Hi @rhine3 sorry for the slow reply on this.

Could you try running the vignettes with the development install?

The source of the issue is the same as in #218 -- the version of `crowsetta` that is available on package indexes is behind the main branch.

My fault for not being clearer about that. I think you are right that pyOpenSci should give reviewers more guidance about which versions to install but we can discuss somewhere not on this issue :stuck_out_tongue:

**Comment by rhine3** [comment]
Hi David, of course! Did you add a download to `bat1_annotation.mat` on “How to use crowsetta with your own annotation format”?

**Comment by NickleDave** [comment]
Ah, sorry, I should have read more carefully the "What happened for each vignette" you provided.  

I will add a download link to that vignette with the file--doing this now.

**Comment by NickleDave** [comment]
@rhine3 added that link to download now.

Writing a to-do list based on your detailed comment abouve:
- [x] include mat file in howto-user-annot.md
- [x] `to_df` method missing should be fixed by local install of code / new release of `crowsetta` after review
- [ ] add `install osfclient` to "unlabeled intervals" vignette
- [ ] fix copy-paste error with code in "unlabeled intervals" vignette
